name: benchmark

env:
  ARCH: x86_64-linux
  AWS_ACCESS_KEY_ID: ${{ vars.LPD_PERF_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LPD_PERF_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.LPD_PERF_AWS_BUCKET }}
  AWS_BUCKET: ${{ vars.LPD_PERF_AWS_REGION }}

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.zig"
      - "src/*.zig"
  pull_request:

    # By default GH trigger on types opened, synchronize and reopened.
    # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    # Since we skip the job when the PR is in draft state, we want to force CI
    # running when the PR is marked ready_for_review w/o other change.
    # see https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
    types: [opened, synchronize, reopened, ready_for_review]

    branches:
      - main
    paths:
      - "src/**/*.zig"
      - "src/*.zig"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmark:
    name: benchmark

    # Don't run the CI with draft PR.
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lightpanda-io/zig-v8:0.12.0-dev.1773-8a8fd47d2
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_CI_PAT }}
          submodules: true

      - name: install v8
        run: |
          mkdir -p vendor/v8/${{env.ARCH}}/debug
          ln -s /usr/local/lib/libc_v8.a vendor/v8/${{env.ARCH}}/debug/libc_v8.a

          mkdir -p vendor/v8/${{env.ARCH}}/release
          ln -s /usr/local/lib/libc_v8.a vendor/v8/${{env.ARCH}}/release/libc_v8.a

      - run: zig build -Doptimize=ReleaseSafe -Dengine=v8
      - name: run benchmark
        run: |
          ./zig-out/bin/jsruntime-bench > benchmark.txt
          cat benchmark.txt

      - name: json output
        run: ./zig-out/bin/jsruntime-bench --json > benchmark.json

      - name: write commit
        run: |
          echo "${{github.sha}}" > commit.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: |
            benchmark.txt
            benchmark.json
            commit.txt

          # configure the retention policy: 10 days on PR and 150 on main.
          retention-days: ${{ github.event_name == 'pull_request' && 10 || 90 }}

  perf-fmt:
    name: perf-fmt
    needs: benchmark

    # Don't execute on PR
    if: github.event_name != 'pull_request'

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lightpanda-io/perf-fmt:latest
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: benchmark-results

      - name: format and send json result
        run: /perf-fmt bench ${{ github.sha }} benchmark.json
