name: zig-test

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.zig"
      - "src/*.zig"
      - "*.zig"
      - ".github/**"
      - "vendor/**"
  pull_request:

    # By default GH trigger on types opened, synchronize and reopened.
    # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    # Since we skip the job when the PR is in draft state, we want to force CI
    # running when the PR is marked ready_for_review w/o other change.
    # see https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
    types: [opened, synchronize, reopened, ready_for_review]

    branches:
      - main
    paths:
      - "src/**/*.zig"
      - "src/*.zig"
      - "*.zig"
      - ".github/**"
      - "vendor/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zig-build-dev:
    name: zig build dev

    # Don't run the CI with draft PR.
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: ./.github/actions/install

      - name: zig build debug
        run: zig build -Dengine=v8

  zig-build-release:
    name: zig build release

    # Don't run the CI with draft PR.
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: ./.github/actions/install

      - name: zig build release
        run: zig build -Doptimize=ReleaseSafe -Dengine=v8

  zig-test:
    name: zig test

    # Don't run the CI with draft PR.
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: ./.github/actions/install

      - name: zig build test
        run: zig build test -Dengine=v8
